apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-grafana

resources:
  - ../../../../common/base/rbac

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: user-grafana
      - op: replace
        path: /metadata/name
        value: cluster-monitoring-view-user-grafana
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: user-grafana
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: grafana-proxy
