apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-grafana

resources:
  - grafana-auth-secret.yaml
  - grafana-vllm-dashboard.yaml
  - grafana-ovms-dashboard.yaml
  - grafana-ovms-community-dashboard.yaml
  - nvidia-vllm-dashboard.yaml
  - amd-vllm-dashboard.yaml
  - gaudi-vllm-dashboard.yaml

