apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-uwm-grafana
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yakovbeder/rhoai-uwm.git
    targetRevision: main
    path: rhoai-uwm-grafana-gitops/overlays/rhoai-uwm-user-grafana-app
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  destination:
    server: https://kubernetes.default.svc
    namespace: user-grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10

