---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-grafana

resources:
  - ../grafana-uwm-user-app
  - ../../../common/base/dashboards

patches:
  # Patch ClusterRoleBinding for cluster-monitoring-view
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: user-grafana
      - op: replace
        path: /metadata/name
        value: cluster-monitoring-view-user-grafana
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
  # Patch RoleBinding for grafana-proxy
  - patch: |-
      - op: add
        path: /subjects/0/namespace
        value: user-grafana
    target:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: grafana-proxy
  # Patch Grafana config for auto-assign org
  - patch: |-
      - op: add
        path: /spec/config/users
        value:
          auto_assign_org: 'true'
          auto_assign_org_id: '1'
          auto_assign_org_role: Admin
    target:
      group: grafana.integreatly.org
      version: v1beta1
      kind: Grafana
      name: grafana
  # Add ArgoCD annotations to dashboards
  - patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1compare-options
        value: IgnoreExtraneous
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: SkipDryRunOnMissingResource=true
    target:
      group: grafana.integreatly.org
      kind: GrafanaDashboard
